### ISSUE TITLE
Should it escape more control and unusual characters?

### ISSUE THREAD

**Issue by mk-pmb** [jadejs/js-stringify#3]
I noticed that `js-stringify` replaces low ASCII control characters with Unicode hex escapes. Should it do similar for some others, like U+0090 device control or U+FEFF zero width no-break space?
My Firefox has no problem with them, as it has no problem with U+0002, so that's probably not the criterion. How do you decide?

PS: In case it helps, here's a list of [characters I consider suspicious](https://gist.github.com/mk-pmb/d750e575d12f1ca595cfe5316235b95e).

**Comment by TimothyGu** [comment]
We escape them because they can possibly contribute to an XSS attack, when the source is directly embedded in an HTML `<script>` tag.

**Comment by ForbesLindesay** [comment]
Yes, there are two types of character we escape in this way:
1. Characters that are not valid in a JavaScript string (`\u2028` and `\u2029`) - needed to prevent bugs
2. Characters that could have special meaning if in an inline script in HTML (`<`, `>`, `/`) - needed to prevent XSS

We don't escape characters that are already escaped by JSON.stringify, or don't fit into one of the two categories above.
